### ISSUE TITLE
How to install the vim with Python 2 in macOS

### ISSUE THREAD

**Issue by chusiang** [chusiang/vimrc#29]
After I upgrade the Python 3.6 to 3.7, I will get warnning message like https://github.com/Valloric/YouCompleteMe/issues/1652

> Error detected while processing function youcompleteme#Enable..80_SetUpPython:

and https://github.com/vim/vim/issues/3117.

> /must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

I see the **MacVim.app** is work on Python 2.

> Check the Python version in Vim. (https://github.com/Valloric/MatchTagAlways/issues/44)
>
>   ```
>   :echo has('python')  => 0
>   :echo has('python3') => 1
>   ```

So I decide switch the Python to 2.7, not 3.7.

> Install the vim with Python 2 in macOS.
>
> ```
> $ brew reinstall vim --with-python@2
> ```

Reference:

1. [Getting a deprecation warning using python 3\.7 · Issue \#44 · Valloric/MatchTagAlways](https://github.com/Valloric/MatchTagAlways/issues/44)
1. [Error message printed first time python3 \(version 3\.7\.0\) dynamic library is imported · Issue \#3117 · vim/vim](https://github.com/vim/vim/issues/3117)

**Comment by chusiang** [comment]
I see my environment is working on Python 2 in the **MacVim.app**,

> Check the Python version in Vim. (https://github.com/Valloric/MatchTagAlways/issues/44)
>
>   ```
>   :echo has('python')  => 0
>   :echo has('python3') => 1
>   ```

so I decide switch the Python to 2.7, not 3.7.

> Install the vim with Python 2 in macOS.
>
> ```
> $ brew reinstall vim --with-python@2
> ==> Reinstalling vim --with-python@2
> ==> Downloading https://github.com/vim/vim/archive/v8.1.0100.tar.gz
> ==> Downloading from https://codeload.github.com/vim/vim/tar.gz/v8.1.0100
> ######################################################################## 100.0%
> ==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/8.1.0100_2/share/man --enabl
> ==> make
> ==> make install prefix=/usr/local/Cellar/vim/8.1.0100_2 STRIP=/usr/bin/true
> 🍺  /usr/local/Cellar/vim/8.1.0100_2: 1,432 files, 23.3MB, built in 1 minute 28 seconds
> ```

Reference:

1. [Getting a deprecation warning using python 3\.7 · Issue \#44 · Valloric/MatchTagAlways](https://github.com/Valloric/MatchTagAlways/issues/44)
1. [Error message printed first time python3 \(version 3\.7\.0\) dynamic library is imported · Issue \#3117 · vim/vim](https://github.com/vim/vim/issues/3117)

**Comment by RanchoCooper** [comment]
Regardless of installed plugins, silently execute python3 once on the top of your `vimrc`:

```
if has('python3')
  silent! python3 1
endif
```
