### ISSUE TITLE
Support the EditorConfig.

### ISSUE THREAD

**Issue by chusiang** [chusiang/vimrc#31]
目前的 vimrc 會造成 EditorConfig 無法作用，並已在乾淨的 Vim 環境確認為組態的問題。這下得一個一個設定檔慢慢試，麻煩了。

**Comment by chusiang** [comment]
先簡單列出相關的連結：

1. [EditorConfig](https://editorconfig.org/#file-location)
1. [editorconfig/editorconfig-vim: EditorConfig plugin for Vim](https://github.com/editorconfig/editorconfig-vim)
1. [editorconfig-vim/editorconfig.txt at master · editorconfig/editorconfig-vim](https://github.com/editorconfig/editorconfig-vim/blob/master/doc/editorconfig.txt)
1. [EditorConfig – 佛祖球球](https://blog.johnsonlu.org/vim-editorconfig/)
1. [EditorConfig使用介绍——解决markdown文件行尾空格自动删除的问题 - chenhao.ch - SegmentFault 思否](https://segmentfault.com/a/1190000007599845)
1. [MacのvimでEditorConfigを効かせるハナシ - Qiita](https://qiita.com/fukuit/items/6d50e65bb57418329867)

**Comment by wenlixiao** [comment]
请教一下,windows下的vundle安装插件报错是什么原因呢


xiao.wenli@qq.com
 
From: Chu-Siang Lai
Date: 2019-07-24 14:20
To: chusiang/vimrc
CC: Subscribed
Subject: Re: [chusiang/vimrc] Support the EditorConfig. (#31)
先簡單列出相關的連結：
EditorConfig
editorconfig/editorconfig-vim: EditorConfig plugin for Vim
editorconfig-vim/editorconfig.txt at master · editorconfig/editorconfig-vim
EditorConfig – 佛祖球球
EditorConfig使用介绍——解决markdown文件行尾空格自动删除的问题 - chenhao.ch - SegmentFault 思否
MacのvimでEditorConfigを効かせるハナシ - Qiita

**Comment by chusiang** [comment]
We can use `EditorConfig_verbose` args to debug.

> https://github.com/editorconfig/editorconfig-vim/blob/master/doc/editorconfig.txt#L131

```
                                             *g:EditorConfig_verbose*
 Set this to 1 if you want debug info printed:
 >
  let g:EditorConfig_verbose = 1
 <
```

1. Add `let g:EditorConfig_verbose = 1` into the vimrc.

    ```
    $ vim ~/.vimrc
    ...

    let g:EditorConfig_verbose = 1
    ```

1. See the debug message at open file.

    ![Screen Shot 2019-07-24 at 14 35 17](https://user-images.githubusercontent.com/219066/61770762-9d22c980-ae20-11e9-9c21-9503031ba18d.png)

**Comment by chusiang** [comment]
After I mark the `filetype indent on` args in `_vim/01.vimrc.vim`, the EditorConfig is working !

> https://github.com/chusiang/vimrc/blob/d2913b433e76e0be9eb4738518e9e201d7a66357/_vim/01.vimrc.vim#L68

Use `ag` to search `filetype indent on` under this project.

```
[ chusiang@gundam ~/.vim ] - 14:44
$ ag 'filetype indent on'
01.vimrc.vim
71:"filetype indent on

bundle/repos/github.com/chusiang/vimcdoc-tw/doc/filetype.twx
76:     :filetype indent on
104::filetype indent on         開啟    未改變  開啟

bundle/repos/github.com/chusiang/vimcdoc-tw/doc/usr_30.twx
256:    :filetype indent on

bundle/repos/github.com/chusiang/vimcdoc-tw/doc/version6.twx
490:":filetype indent on" 命令允許使用提供的縮排指令碼。使用者手冊有解釋: |30.3|。

bundle/repos/github.com/plasticboy/vim-markdown/test/vimrc
12:filetype indent on

bundle/repos/github.com/Shougo/dein.vim/autoload/dein/autoload.vim
313:    silent! filetype indent on
```

I think I will disable it first.

----

Reference:

* [vi/vim使用进阶: 开启文件类型检测 - 易水博客](https://blog.easwy.com/archives/advanced-vim-skills-filetype-on/)

**Comment by chusiang** [comment]
Hi @wenlixiao ,

Vim 有許多套件 (plugin) 會用到 unix-like 的 libray，在*純* Windows 的環境很容易出問題，建議還是在 VM (虛擬機器) 或 Docker Container (容器) 底下，跑 Linux 用 Vim 會比較好。

加油。

**Comment by wenlixiao** [comment]
Thks



xiao.wenli@qq.com
 
From: Chu-Siang Lai
Date: 2019-07-24 15:01
To: chusiang/vimrc
CC: Emoh; Mention
Subject: Re: [chusiang/vimrc] Support the EditorConfig. (#31)
Hi @wenlixiao ,
Vim 有許多套件 (plugin) 會用到 unix-like 的 libray，在純 Windows 的環境很容易出問題，建議還是在 VM (虛擬機器) 或 Docker Container (容器) 底下，跑 Linux 用 Vim 會比較好。
加油。

**Comment by chusiang** [comment]
Fixed at v4.0.5.

> https://github.com/chusiang/vimrc/releases/tag/4.0.5

**Comment by wenlixiao** [comment]
@chusiang 您是做运维还是开发,感觉段位好高.



xiao.wenli@qq.com
 
From: Chu-Siang Lai
Date: 2019-07-24 15:01
To: chusiang/vimrc
CC: Emoh; Mention
Subject: Re: [chusiang/vimrc] Support the EditorConfig. (#31)
Hi @wenlixiao ,
Vim 有許多套件 (plugin) 會用到 unix-like 的 libray，在純 Windows 的環境很容易出問題，建議還是在 VM (虛擬機器) 或 Docker Container (容器) 底下，跑 Linux 用 Vim 會比較好。
加油。

**Comment by chusiang** [comment]
Hi @wenlixiao ,

敝人的是搞基礎建設 (infrastructure)、維運 (Operation)、持續整合 (Continuous Integration)、持續交付 (Continuous Delivery)、監控 (Monitoring) ... 的。以前是系統工程師；今年則被人稱作 SRE 或 DevOps Engineer。

對我們來說，Git、Docker 都算在必備的技藝之一喔！

**Comment by wenlixiao** [comment]
同行啊,敝人也是运维,我是看了你的ansible教程,发现你的vimrc.真的很好,规划的很好,我现在优化了一下,自己在用了.我的运维对象偏向传统,IBM ORACLE EMC之类的.



xiao.wenli@qq.com
 
From: Chu-Siang Lai
Date: 2019-07-25 19:01
To: chusiang/vimrc
CC: Emoh; Mention
Subject: Re: [chusiang/vimrc] Support the EditorConfig. (#31)
Hi @wenlixiao ,
敝人的是搞基礎建設 (infrastructure)、維運 (Operation)、持續整合 (Continuous Integration)、持續交付 (Continuous Delivery)、監控 (Monitoring) ... 的。以前是系統工程師；今年則被人稱作 SRE 或 DevOps Engineer。
對我們來說，Git、Docker 都算在必備的技藝之一喔！

**Comment by chusiang** [comment]
Hi @wenlixiao ,

很高興敝人的小小 Ansible 和 Vim 心得可以幫上您的忙。一起為今天的「提早下班」努力吧！
